hnbgw: put copyright into define
Fix the following compile error, seen on ubuntu 18.04 with GCC 7.5.0,
opensuse 15.4 and our OE builds:

  hnbgw.c:549:15: error: initializer element is not constant
    .copyright = hnbgw_copyright,
                 ^~~~~~~~~~~~~~~

Fixes: 04844415 ("move main() to separate file")
Change-Id: I13b2569a369724e0298b064a0876b95d6dafd9d0