ps_rab_ass_fsm: Fix uninitialized ptr access
/git/osmo-hnbgw/include/osmocom/hnbgw/context_map.h:211:9: error: 'rab' may be used uninitialized [-Werror=maybe-uninitialized]
  211 |         _map_rua_dispatch(MAP, EVENT, MSGB, __FILE__, __LINE__)
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/git/osmo-hnbgw/src/osmo-hnbgw/ps_rab_ass_fsm.c:358:9: note: in expansion of macro 'map_rua_dispatch'
  358 |         map_rua_dispatch(rab->map, MAP_RUA_EV_TX_DIRECT_TRANSFER, msg);
      |         ^~~~~~~~~~~~~~~~
/git/osmo-hnbgw/src/osmo-hnbgw/ps_rab_ass_fsm.c:297:24: note: 'rab' was declared here
  297 |         struct ps_rab *rab;
      |                        ^~~

Change-Id: Ifdcd4c369b35820c5c2beb695392d0b82d4ea34c
(cherry picked from commit 89504050ea481a517d7da68b008c19e83f37aae2)