fixup: compilation error: unused var in map_rua_init_action()
The variable was left unused by recent patch
I3e1ad7a2aa71674a22a27c31512600f2de139032 aka
a5974d7906a333bfd3399f83cc8072b4604f49cd

Change-Id: I871bc43f6f47d4b78fbf88826615f2dbb8e1f807